/* 
 * Copyright 2015 (C) Manuel Domínguez Dorado - ingeniero@ManoloDominguez.com.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package simMPLS.ui.dialogs;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import simMPLS.scenario.TLERNode;
import simMPLS.scenario.TTopology;
import simMPLS.ui.simulator.JPanelDisenio;
import simMPLS.ui.utils.TImagesBroker;

/**
 * Esta clase implementa una ventana que nos permite configurar un nodo LER
 * @author Administrador<B>Manuel Dom�nguez Dorado</B><br><A
 * href="mailto:ingeniero@ManoloDominguez.com">ingeniero@ManoloDominguez.com</A><br><A href="http://www.ManoloDominguez.com" target="_blank">http://www.ManoloDominguez.com</A>
 * @version 1.0
 */
public class JVentanaLER extends javax.swing.JDialog {
    
    /**
     * Este m�todo crea una nueva instancia de JVentanaconfigLER
     * @param t Topolog�a dentro del a cual se encuentra insertado el LER que queremos
     * configurar.
     * @param pad Panel de dise�o dentro del cual estamos dise�ando el LER que queremos
     * configurar.
     * @param di Dispensador de im�genes global de la aplicaci�n.
     * @param parent Ventana padre dentro de la cual se ubicar� esta ventana de tipo JVentanaLER
     * @param modal TRUE indica que la ventana impedir� que se pueda seleccionar nada de la interfaz
     * de usuario hasta que se cierre. FALSE indica que esto no es asi.
     * @since 1.0
     */
    public JVentanaLER(TTopology t, JPanelDisenio pad, TImagesBroker di, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        ventanaPadre = parent;
        dispensadorDeImagenes = di;
        pd = pad;
        topo = t;
        initComponents();
        initComponents2();
    }
    
    /**
     * Este m�todo terminar� de configurar aspectos de la clase que no han podido ser
     * definidos en el constructor.
     * @since 1.0
     */
    public void initComponents2() {
        panelCoordenadas.ponerPanelOrigen(pd);
        java.awt.Dimension tamFrame=this.getSize();
        java.awt.Dimension tamPadre=ventanaPadre.getSize();
        setLocation((tamPadre.width-tamFrame.width)/2, (tamPadre.height-tamFrame.height)/2);
        configLER=null;
        coordenadaX.setText(java.util.ResourceBundle.getBundle("simMPLS/lenguajes/lenguajes").getString("JVentanaLER.X=") + panelCoordenadas.obtenerXReal());
        coordenadaY.setText(java.util.ResourceBundle.getBundle("simMPLS/lenguajes/lenguajes").getString("JVentanaLER.Y=") + panelCoordenadas.obtenerYReal());
        BKUPMostrarNombre = true;
        BKUPNombre = "";
        BKUPPotencia = 0;
        BKUPTamBuffer = 0;
        reconfigurando = false;
        BKUPGenerarEstadisticas = false;
        this.selectorSencilloCaracteristicas.removeAllItems();
        this.selectorSencilloCaracteristicas.addItem(java.util.ResourceBundle.getBundle("simMPLS/lenguajes/lenguajes").getString("JVentanaLER.Personalized_LER"));
        this.selectorSencilloCaracteristicas.addItem(java.util.ResourceBundle.getBundle("simMPLS/lenguajes/lenguajes").getString("JVentanaLER.Very_low_range_LER"));
        this.selectorSencilloCaracteristicas.addItem(java.util.ResourceBundle.getBundle("simMPLS/lenguajes/lenguajes").getString("JVentanaLER.Low_range_LER"));
        this.selectorSencilloCaracteristicas.addItem(java.util.ResourceBundle.getBundle("simMPLS/lenguajes/lenguajes").getString("JVentanaLER.Medium_range_LER"));
        this.selectorSencilloCaracteristicas.addItem(java.util.ResourceBundle.getBundle("simMPLS/lenguajes/lenguajes").getString("High_range_LER"));
        this.selectorSencilloCaracteristicas.addItem(java.util.ResourceBundle.getBundle("simMPLS/lenguajes/lenguajes").getString("JVentanaLER.Very_high_range_LER"));
        this.selectorSencilloCaracteristicas.setSelectedIndex(0);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelPestanias = new javax.swing.JTabbedPane();
        panelGeneral = new javax.swing.JPanel();
        iconoLER = new javax.swing.JLabel();
        etiquetaNombre = new javax.swing.JLabel();
        nombreNodo = new javax.swing.JTextField();
        panelPosicion = new javax.swing.JPanel();
        coordenadaX = new javax.swing.JLabel();
        coordenadaY = new javax.swing.JLabel();
        panelCoordenadas = new simMPLS.ui.dialogs.JPanelCoordenadas();
        verNombre = new javax.swing.JCheckBox();
        panelRapido = new javax.swing.JPanel();
        selectorDeGenerarEstadisticasSencillo = new javax.swing.JCheckBox();
        iconoEnlace1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        selectorSencilloCaracteristicas = new javax.swing.JComboBox();
        panelAvanzado = new javax.swing.JPanel();
        selectorDeGenerarEstadisticasAvanzado = new javax.swing.JCheckBox();
        iconoEnlace2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        selectorDePotenciaDeConmutacion = new javax.swing.JSlider();
        etiquetaPotencia = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        selectorDeTamanioBuffer = new javax.swing.JSlider();
        etiquetaMemoriaBuffer = new javax.swing.JLabel();
        panelConfiguration = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ipAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        checkBoxTTLPropagate = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        checkBoxPHP = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        checkBoxLDP = new javax.swing.JCheckBox();
        panelBotones = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("simMPLS/lenguajes/lenguajes"); // NOI18N
        setTitle(bundle.getString("VentanaLER.titulo")); // NOI18N
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPestanias.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        panelGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconoLER.setIcon(dispensadorDeImagenes.obtenerIcono(simMPLS.ui.utils.TImagesBroker.LER));
        iconoLER.setText(bundle.getString("VentanaLER.descripcion")); // NOI18N
        panelGeneral.add(iconoLER, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 20, 335, -1));

        etiquetaNombre.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        etiquetaNombre.setText(bundle.getString("VentanaLER.etiquetaNombre")); // NOI18N
        panelGeneral.add(etiquetaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 80, 120, -1));
        panelGeneral.add(nombreNodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 105, 125, -1));

        panelPosicion.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("VentanaLER.etiquetaGrupo"))); // NOI18N
        panelPosicion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        coordenadaX.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        coordenadaX.setText(bundle.getString("VentanaLER.X=")); // NOI18N
        panelPosicion.add(coordenadaX, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        coordenadaY.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        coordenadaY.setText(bundle.getString("VentanaLER.Y=")); // NOI18N
        panelPosicion.add(coordenadaY, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        panelCoordenadas.setBackground(new java.awt.Color(255, 255, 255));
        panelCoordenadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clicEnPanelCoordenadas(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratonEntraEnPanelCoordenadas(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ratonSaleDePanelCoordenadas(evt);
            }
        });
        panelPosicion.add(panelCoordenadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 25, 130, 70));

        panelGeneral.add(panelPosicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 75, 180, 125));

        verNombre.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        verNombre.setSelected(true);
        verNombre.setText(bundle.getString("VentanaLER.verNombre")); // NOI18N
        panelGeneral.add(verNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 135, -1, -1));

        panelPestanias.addTab(bundle.getString("VentanaLER.tabs.General"), panelGeneral); // NOI18N

        panelRapido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        selectorDeGenerarEstadisticasSencillo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        selectorDeGenerarEstadisticasSencillo.setText(bundle.getString("VentanaLER.GenerarEstadisticas")); // NOI18N
        selectorDeGenerarEstadisticasSencillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicEnGenerarEstadisticasSencillo(evt);
            }
        });
        panelRapido.add(selectorDeGenerarEstadisticasSencillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        iconoEnlace1.setIcon(dispensadorDeImagenes.obtenerIcono(simMPLS.ui.utils.TImagesBroker.ASISTENTE));
        iconoEnlace1.setText(bundle.getString("VentanaLER.ConfiguracionRapida")); // NOI18N
        panelRapido.add(iconoEnlace1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 20, 335, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText(bundle.getString("VentanaLER.CaracteristicasDelLER")); // NOI18N
        panelRapido.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 160, -1));

        selectorSencilloCaracteristicas.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        selectorSencilloCaracteristicas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Personalized", "Very low cost LER", "Low cost LER", "Medium cost LER", "Expensive LER", "Very expensive LER" }));
        selectorSencilloCaracteristicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cliEnSelectorSencilloCaracteristicas(evt);
            }
        });
        panelRapido.add(selectorSencilloCaracteristicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        panelPestanias.addTab(bundle.getString("VentanaLER.tabs.Fast"), panelRapido); // NOI18N

        panelAvanzado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        selectorDeGenerarEstadisticasAvanzado.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        selectorDeGenerarEstadisticasAvanzado.setText(bundle.getString("VentanaLER.GenerarEstadisticas")); // NOI18N
        selectorDeGenerarEstadisticasAvanzado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicEnGenerarEstadisticasAvanzada(evt);
            }
        });
        panelAvanzado.add(selectorDeGenerarEstadisticasAvanzado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        iconoEnlace2.setIcon(dispensadorDeImagenes.obtenerIcono(simMPLS.ui.utils.TImagesBroker.AVANZADA));
        iconoEnlace2.setText(bundle.getString("VentanaLER.ConfiguracionAvanzada")); // NOI18N
        panelAvanzado.add(iconoEnlace2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 20, 335, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText(bundle.getString("VentanaLER.PotenciaDeConmutacion")); // NOI18N
        panelAvanzado.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 140, -1));

        selectorDePotenciaDeConmutacion.setMajorTickSpacing(1000);
        selectorDePotenciaDeConmutacion.setMaximum(10240);
        selectorDePotenciaDeConmutacion.setMinimum(1);
        selectorDePotenciaDeConmutacion.setMinorTickSpacing(100);
        selectorDePotenciaDeConmutacion.setValue(1);
        selectorDePotenciaDeConmutacion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                selectorDePotenciadeConmutacionCambiado(evt);
            }
        });
        panelAvanzado.add(selectorDePotenciaDeConmutacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 90, 130, 20));

        etiquetaPotencia.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        etiquetaPotencia.setForeground(new java.awt.Color(102, 102, 102));
        etiquetaPotencia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etiquetaPotencia.setText(bundle.getString("VentanaLER.1_Mbps")); // NOI18N
        panelAvanzado.add(etiquetaPotencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 70, 20));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText(bundle.getString("VentanaLER.TamanioDelBufferDeEntrada")); // NOI18N
        panelAvanzado.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 180, -1));

        selectorDeTamanioBuffer.setMajorTickSpacing(50);
        selectorDeTamanioBuffer.setMaximum(1024);
        selectorDeTamanioBuffer.setMinimum(1);
        selectorDeTamanioBuffer.setMinorTickSpacing(100);
        selectorDeTamanioBuffer.setValue(1);
        selectorDeTamanioBuffer.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                selectorDeTamanioBufferCambiado(evt);
            }
        });
        panelAvanzado.add(selectorDeTamanioBuffer, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 100, 20));

        etiquetaMemoriaBuffer.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        etiquetaMemoriaBuffer.setForeground(new java.awt.Color(102, 102, 102));
        etiquetaMemoriaBuffer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etiquetaMemoriaBuffer.setText(bundle.getString("VentanaLER.1_MB")); // NOI18N
        panelAvanzado.add(etiquetaMemoriaBuffer, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 60, 20));

        panelPestanias.addTab(bundle.getString("VentanaLER.tabs.Advanced"), panelAvanzado); // NOI18N

        panelConfiguration.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Configuration of the node");
        panelConfiguration.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel5.setText("IP address :");
        panelConfiguration.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));
        panelConfiguration.add(ipAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 160, -1));

        jLabel6.setText("Propagate-TTL:");
        panelConfiguration.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));
        panelConfiguration.add(checkBoxTTLPropagate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        jLabel7.setText("Penultimate Hop Popping:");
        panelConfiguration.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));
        panelConfiguration.add(checkBoxPHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        jLabel8.setText("LDP:");
        panelConfiguration.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));
        panelConfiguration.add(checkBoxLDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        panelPestanias.addTab("Configuration", panelConfiguration);

        panelPrincipal.add(panelPestanias, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 370, 240));

        panelBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButton2.setIcon(dispensadorDeImagenes.obtenerIcono(simMPLS.ui.utils.TImagesBroker.ACEPTAR));
        jButton2.setMnemonic(java.util.ResourceBundle.getBundle("simMPLS/lenguajes/lenguajes").getString("VentanaLER.botones.mne.Aceptar").charAt(0));
        jButton2.setText(bundle.getString("VentanaLER.boton.Ok")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicEnAceptar(evt);
            }
        });
        panelBotones.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 115, -1));

        jButton3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButton3.setIcon(dispensadorDeImagenes.obtenerIcono(simMPLS.ui.utils.TImagesBroker.CANCELAR));
        jButton3.setMnemonic(java.util.ResourceBundle.getBundle("simMPLS/lenguajes/lenguajes").getString("VentanaLER.botones.mne.Cancelar").charAt(0));
        jButton3.setText(bundle.getString("VentanaLER.boton.Cancel")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicEnCancelar(evt);
            }
        });
        panelBotones.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 15, 115, -1));

        panelPrincipal.add(panelBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 255, 400, 55));

        getContentPane().add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cliEnSelectorSencilloCaracteristicas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cliEnSelectorSencilloCaracteristicas
        int opcionSeleccionada = this.selectorSencilloCaracteristicas.getSelectedIndex();
        if (opcionSeleccionada == 0) {
            // No se hace nada
            this.selectorSencilloCaracteristicas.setSelectedIndex(0);
        } else if (opcionSeleccionada == 1) {
            this.selectorDePotenciaDeConmutacion.setValue(1);
            this.selectorDeTamanioBuffer.setValue(1);
            this.selectorSencilloCaracteristicas.setSelectedIndex(1);
        } else if (opcionSeleccionada == 2) {
            this.selectorDePotenciaDeConmutacion.setValue(2560);
            this.selectorDeTamanioBuffer.setValue(256);
            this.selectorSencilloCaracteristicas.setSelectedIndex(2);
        } else if (opcionSeleccionada == 3) {
            this.selectorDePotenciaDeConmutacion.setValue(5120);
            this.selectorDeTamanioBuffer.setValue(512);
            this.selectorSencilloCaracteristicas.setSelectedIndex(3);
        } else if (opcionSeleccionada == 4) {
            this.selectorDePotenciaDeConmutacion.setValue(7680);
            this.selectorDeTamanioBuffer.setValue(768);
            this.selectorSencilloCaracteristicas.setSelectedIndex(4);
        } else if (opcionSeleccionada == 5) {
            this.selectorDePotenciaDeConmutacion.setValue(10240);
            this.selectorDeTamanioBuffer.setValue(1024);
            this.selectorSencilloCaracteristicas.setSelectedIndex(5);
        }
    }//GEN-LAST:event_cliEnSelectorSencilloCaracteristicas

    private void selectorDeTamanioBufferCambiado(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_selectorDeTamanioBufferCambiado
        this.selectorSencilloCaracteristicas.setSelectedIndex(0);
        this.etiquetaMemoriaBuffer.setText(this.selectorDeTamanioBuffer.getValue() + " " + java.util.ResourceBundle.getBundle("simMPLS/lenguajes/lenguajes").getString("VentanaLER.MB"));
    }//GEN-LAST:event_selectorDeTamanioBufferCambiado

    private void selectorDePotenciadeConmutacionCambiado(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_selectorDePotenciadeConmutacionCambiado
        this.selectorSencilloCaracteristicas.setSelectedIndex(0);
        this.etiquetaPotencia.setText(this.selectorDePotenciaDeConmutacion.getValue() + " " + java.util.ResourceBundle.getBundle("simMPLS/lenguajes/lenguajes").getString("VentanaLER.Mbps."));
    }//GEN-LAST:event_selectorDePotenciadeConmutacionCambiado

    private void clicEnGenerarEstadisticasAvanzada(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clicEnGenerarEstadisticasAvanzada
        this.selectorDeGenerarEstadisticasSencillo.setSelected(this.selectorDeGenerarEstadisticasAvanzado.isSelected());
    }//GEN-LAST:event_clicEnGenerarEstadisticasAvanzada

    private void clicEnGenerarEstadisticasSencillo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clicEnGenerarEstadisticasSencillo
        this.selectorDeGenerarEstadisticasAvanzado.setSelected(this.selectorDeGenerarEstadisticasSencillo.isSelected());
    }//GEN-LAST:event_clicEnGenerarEstadisticasSencillo
    
private void clicEnCancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clicEnCancelar
    if (reconfigurando) {
        configLER.setShowName(BKUPMostrarNombre);
        configLER.setName(BKUPNombre);
        configLER.setIPAddress(BKUPIP);
        configLER.setPropagateTTL(BKUPTTLPropagate);
        configLER.setPHP(BKUPPHP);
        configLER.setLDP(BKUPLDP);
        configLER.setWellConfigured(true);
        configLER.ponerTamanioBuffer(BKUPTamBuffer);
        configLER.ponerPotenciaEnMb(BKUPPotencia);
        configLER.setGenerateStats(BKUPGenerarEstadisticas);
        reconfigurando = false;
    } else {
        configLER.setWellConfigured(false);
    }
    this.setVisible(false);
    this.dispose();
}//GEN-LAST:event_clicEnCancelar

private void clicEnAceptar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clicEnAceptar
    configLER.setWellConfigured(true);
    if (!this.reconfigurando){
        configLER.setPosition(new Point(panelCoordenadas.obtenerXReal(),panelCoordenadas.obtenerYReal()));
    }
    configLER.ponerTamanioBuffer(this.selectorDeTamanioBuffer.getValue());
    configLER.ponerPotenciaEnMb(this.selectorDePotenciaDeConmutacion.getValue());
    configLER.setGenerateStats(this.selectorDeGenerarEstadisticasSencillo.isSelected());
    configLER.setName(nombreNodo.getText());
    configLER.setShowName(verNombre.isSelected());
    configLER.setGenerateStats(this.selectorDeGenerarEstadisticasSencillo.isSelected());
    configLER.setPropagateTTL(this.checkBoxTTLPropagate.isSelected());
    configLER.setPHP(this.checkBoxPHP.isSelected());
    configLER.setLDP(this.checkBoxLDP.isSelected());
    if(ipAddress.getText().isEmpty()== false || this.reconfigurando){
        configLER.setIPAddress(ipAddress.getText());
    }
    int error = configLER.validateConfig(topo, this.reconfigurando);
    if (error != TLERNode.CORRECTA) {
        JVentanaAdvertencia va = new JVentanaAdvertencia(ventanaPadre, true, dispensadorDeImagenes);
        va.mostrarMensaje(configLER.getErrorMessage(error));
        va.show();
    } else {
        this.setVisible(false);
        this.dispose();
    }
}//GEN-LAST:event_clicEnAceptar

private void clicEnPanelCoordenadas(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clicEnPanelCoordenadas
    if (evt.getButton() == MouseEvent.BUTTON1) {
        panelCoordenadas.ponerCoordenadasReducidas(evt.getPoint());
        coordenadaX.setText(java.util.ResourceBundle.getBundle("simMPLS/lenguajes/lenguajes").getString("VentanaconfigLER.X=_") + panelCoordenadas.obtenerXReal());
        coordenadaY.setText(java.util.ResourceBundle.getBundle("simMPLS/lenguajes/lenguajes").getString("VentanaconfigLER.Y=_") + panelCoordenadas.obtenerYReal());
        panelCoordenadas.repaint();
    }
}//GEN-LAST:event_clicEnPanelCoordenadas

private void ratonSaleDePanelCoordenadas(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratonSaleDePanelCoordenadas
    this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
}//GEN-LAST:event_ratonSaleDePanelCoordenadas

private void ratonEntraEnPanelCoordenadas(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratonEntraEnPanelCoordenadas
    this.setCursor(new Cursor(Cursor.CROSSHAIR_CURSOR));
}//GEN-LAST:event_ratonEntraEnPanelCoordenadas

/** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        configLER.setWellConfigured(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * Este m�todo permite cargar en la ventana la configuraci�n actual del LER.
     * @since 1.0
     * @param tnler El nodo LER que queremos configurar.
     * @param recfg TRUE indica que estamos reconfigurando el LER. FALSE indica que el LER se ha
     * insertado nuevo en la topolog�a.
     */
    public void ponerConfiguracion(TLERNode tnler, boolean recfg) {
        configLER = tnler;
        reconfigurando = recfg;
        if (reconfigurando) {
            this.panelCoordenadas.setEnabled(false);
            this.panelCoordenadas.setToolTipText(null);

            BKUPGenerarEstadisticas = tnler.isGeneratingStats();
            BKUPMostrarNombre = tnler.getShowName();
            BKUPNombre = tnler.getName();
            BKUPIP = tnler.getIPAddress();
            BKUPTTLPropagate = tnler.isPropagateTTL();
            BKUPPHP = tnler.isPHP();
            BKUPLDP = tnler.isLDP();
            BKUPPotencia = tnler.obtenerPotenciaEnMb();
            BKUPTamBuffer = tnler.obtenerTamanioBuffer();

            this.selectorDeGenerarEstadisticasAvanzado.setSelected(BKUPGenerarEstadisticas);
            this.selectorDeGenerarEstadisticasSencillo.setSelected(BKUPGenerarEstadisticas);
            this.selectorDePotenciaDeConmutacion.setValue(BKUPPotencia);
            this.selectorDeTamanioBuffer.setValue(BKUPTamBuffer);
            this.nombreNodo.setText(BKUPNombre);
            this.ipAddress.setText(BKUPIP);
            this.checkBoxTTLPropagate.setSelected(BKUPTTLPropagate);
            this.checkBoxPHP.setSelected(BKUPPHP);
            this.checkBoxLDP.setSelected(BKUPLDP);
            this.verNombre.setSelected(BKUPMostrarNombre);
        }
    }
    
    private TImagesBroker dispensadorDeImagenes;
    private Frame ventanaPadre;
    private JPanelDisenio pd;
    private TLERNode configLER;
    private TTopology topo;
    
    private boolean BKUPMostrarNombre;
    private String BKUPNombre;
    private String BKUPIP;
    private boolean BKUPTTLPropagate;
    private boolean BKUPPHP;
    private boolean BKUPLDP;
    private int BKUPPotencia;
    private int BKUPTamBuffer;
    private boolean BKUPGenerarEstadisticas;

    private boolean reconfigurando;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBoxLDP;
    private javax.swing.JCheckBox checkBoxPHP;
    private javax.swing.JCheckBox checkBoxTTLPropagate;
    private javax.swing.JLabel coordenadaX;
    private javax.swing.JLabel coordenadaY;
    private javax.swing.JLabel etiquetaMemoriaBuffer;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaPotencia;
    private javax.swing.JLabel iconoEnlace1;
    private javax.swing.JLabel iconoEnlace2;
    private javax.swing.JLabel iconoLER;
    private javax.swing.JTextField ipAddress;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nombreNodo;
    private javax.swing.JPanel panelAvanzado;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelConfiguration;
    private simMPLS.ui.dialogs.JPanelCoordenadas panelCoordenadas;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JTabbedPane panelPestanias;
    private javax.swing.JPanel panelPosicion;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelRapido;
    private javax.swing.JCheckBox selectorDeGenerarEstadisticasAvanzado;
    private javax.swing.JCheckBox selectorDeGenerarEstadisticasSencillo;
    private javax.swing.JSlider selectorDePotenciaDeConmutacion;
    private javax.swing.JSlider selectorDeTamanioBuffer;
    private javax.swing.JComboBox selectorSencilloCaracteristicas;
    private javax.swing.JCheckBox verNombre;
    // End of variables declaration//GEN-END:variables
    
}
